# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgVWnxxb_suexpbY26FNHLCj5GkhwuJD
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, Flatten, Dot, Dense
from tensorflow.keras.models import Model

# Load MovieLens dataset
data = pd.read_csv('rating.csv')  # Ensure this path is correct

# Create mappings for user and movie IDs
user_ids = data['userId'].unique().tolist()
movie_ids = data['movieId'].unique().tolist()  # Use 'movieId' instead of 'item_id'

user2idx = {u: i for i, u in enumerate(user_ids)}
movie2idx = {m: i for i, m in enumerate(movie_ids)}  # Renamed from item2idx to movie2idx

# Map original IDs to indices
data['user_idx'] = data['userId'].map(user2idx)
data['movie_idx'] = data['movieId'].map(movie2idx)  # Column renamed to 'movie_idx'

# Define model parameters
n_users = len(user_ids)
n_movies = len(movie_ids)  # Renamed from n_items
embedding_dim = 10

# Build the model
user_input = Input(shape=(1,))
user_embedding = Embedding(n_users, embedding_dim)(user_input)
user_vec = Flatten()(user_embedding)

movie_input = Input(shape=(1,))  # Renamed from item_input
movie_embedding = Embedding(n_movies, embedding_dim)(movie_input)  # Renamed
movie_vec = Flatten()(movie_embedding)

dot_product = Dot(axes=1)([user_vec, movie_vec])
output = Dense(1)(dot_product)  # Predict rating (1-5)

model = Model(inputs=[user_input, movie_input], outputs=output)
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Train-test split
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2, random_state=42)

# Train the model
model.fit(
    [train['user_idx'], train['movie_idx']],  # Use 'movie_idx' instead of 'item_idx'
    train['rating'],
    epochs=10,
    batch_size=64,
    validation_data=([test['user_idx'], test['movie_idx']], test['rating'])
)

# Evaluate
model.evaluate([test['user_idx'], test['movie_idx']], test['rating'])

# Recommendation function
def recommend(user_id, top_k=5):
    user_idx = user2idx[user_id]
    all_movies = np.array(list(movie2idx.values()))  # Use movie2idx instead of item2idx
    user_array = np.array([user_idx] * len(all_movies))
    pred_ratings = model.predict([user_array, all_movies]).flatten()
    top_indices = np.argsort(pred_ratings)[-top_k:][::-1]
    return [movie_ids[i] for i in top_indices]  # Return original movie IDs

# Example: Recommend top 5 movies for userId=10
print(recommend(10))